manifestVersion = 0

[package]
  type = "mod"
  name = "minepkg-companion"
  description = "A helper mod for minepkg. It would be lonely without it."
  license = "MIT"
  version = "0.1.0"

[requirements]
  minecraft = "~1.14.0"
  fabric = "*"

[dependencies]
  # none

[hooks]
  build = "./gradlew build -x test"
