manifestVersion = 0

[package]
  type = "mod"
  name = "minepkg-companion"
  description = "A helper mod for minepkg. It would be lonely without it."
  version = "0.3.3"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.16.0"
  fabric = "*"

[dependencies]

[dev]
  buildCommand = "./gradlew build"
