
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "minepkg-companion"
  description = "A helper mod for minepkg. It would be lonely without it."
  version = "0.3.4"
  platform = "fabric"
  license = "MIT"

# These are global requirements
[requirements]
  minecraft = "~1.17.0"
  fabric = "*"
  minepkgCompanion = "none"

[dependencies]

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    fabric = "^0.36.0"
