manifestVersion = 0

[package]
  type = "modpack"
  name = "minepkg-companion-test"
  description = "Test modpack. pls ignore"
  license = "MIT"
  version = "0.1.0"

[requirements]
  minecraft = "1.15.x"
  fabric = "*"
  minepkgCompanion = "none"
